import { NextRequest, NextResponse } from "next/server";
import { and, eq, isNull, sql } from "drizzle-orm";
import { db } from "@/db";
import { items, loans, movements } from "@/db/schema";
import { apiAuthGuard } from "@/lib/auth";
type Ctx = { params: Promise<{ id: string }> };
export async function POST(request: NextRequest, ctx: Ctx) {
  const denied = await apiAuthGuard(); if (denied) return denied;
  const { id: raw } = await ctx.params; const itemId = Number(raw); const body = await request.json().catch(() => null);
  const borrower = typeof body?.borrower === "string" ? body.borrower.trim() : ""; const quantity = Math.floor(Number(body?.quantity) || 1);
  if (!Number.isInteger(itemId) || !borrower || borrower.length > 160 || quantity < 1) return NextResponse.json({ error: "Datos de préstamo no válidos." }, { status: 400 });
  try { const result = await db.transaction(async (tx) => { const [item] = await tx.select().from(items).where(and(eq(items.id, itemId), isNull(items.deletedAt))).for("update"); if (!item) throw new Error("NOT_FOUND"); if (item.itemType === "CONTABLE" && quantity > item.quantity) throw new Error(`STOCK:${item.quantity}`); if (item.itemType === "UNICO" && item.status === "PRESTADO") throw new Error("ALREADY"); const [loan] = await tx.insert(loans).values({ itemId, borrower, responsible: String(body.responsible ?? "").trim().slice(0, 160) || null, quantity: item.itemType === "UNICO" ? 1 : quantity, dueAt: body.dueAt ? new Date(body.dueAt) : null, notes: String(body.notes ?? "").trim().slice(0, 500) || null }).returning(); await tx.update(items).set({ status: "PRESTADO", quantity: item.itemType === "CONTABLE" ? item.quantity - quantity : 1, version: sql`${items.version} + 1`, updatedAt: new Date() }).where(eq(items.id, itemId)); await tx.insert(movements).values({ itemId, type: "PRESTAMO", quantity, note: `Prestado a ${borrower}${body.dueAt ? ` · devolución ${body.dueAt}` : ""}` }); return loan; }); return NextResponse.json(result, { status: 201 }); } catch (e) { const m = e instanceof Error ? e.message : ""; if (m.startsWith("STOCK:")) return NextResponse.json({ error: `Stock insuficiente: ${m.split(":")[1]} uds.` }, { status: 400 }); if (m === "ALREADY") return NextResponse.json({ error: "La pieza ya figura prestada." }, { status: 409 }); return NextResponse.json({ error: "No se pudo registrar el préstamo." }, { status: m === "NOT_FOUND" ? 404 : 500 }); }
}
export async function PATCH(request: NextRequest, ctx: Ctx) {
  const denied = await apiAuthGuard(); if (denied) return denied; const { id: raw } = await ctx.params; const itemId = Number(raw); const body = await request.json().catch(() => null); const loanId = Number(body?.loanId);
  if (!Number.isInteger(loanId)) return NextResponse.json({ error: "Préstamo no válido." }, { status: 400 });
  try { const result = await db.transaction(async (tx) => { const [loan] = await tx.select().from(loans).where(and(eq(loans.id, loanId), eq(loans.itemId, itemId), isNull(loans.returnedAt))).for("update"); if (!loan) throw new Error("NOT_FOUND"); const [item] = await tx.select().from(items).where(eq(items.id, itemId)).for("update"); const [returned] = await tx.update(loans).set({ returnedAt: new Date() }).where(eq(loans.id, loanId)).returning(); await tx.update(items).set({ status: "DISPONIBLE", quantity: item.itemType === "CONTABLE" ? item.quantity + loan.quantity : 1, version: sql`${items.version} + 1`, updatedAt: new Date() }).where(eq(items.id, itemId)); await tx.insert(movements).values({ itemId, type: "DEVOLUCION", quantity: loan.quantity, note: `Devuelto por ${loan.borrower}` }); return returned; }); return NextResponse.json(result); } catch { return NextResponse.json({ error: "Préstamo no encontrado o ya devuelto." }, { status: 404 }); }
}
