"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, FileSpreadsheet, Loader2, Upload } from "lucide-react";
import { secureFetch } from "@/lib/secure-fetch";
import { Button } from "@/components/ui";
type Row={row:number;name:string;zoneId?:number;zone:string;category:string;type:string;quantity:number;status:string;condition:string;errors:string[]};
export function ImportInventory(){const[rows,setRows]=useState<Row[]>([]);const[csv,setCsv]=useState("");const[pending,setPending]=useState(false);const[message,setMessage]=useState<string|null>(null);const invalid=rows.filter(r=>r.errors.length).length;
async function validate(text:string,commit=false){setPending(true);const res=await secureFetch(`/api/import${commit?"?commit=1":""}`,{method:"POST",headers:{"Content-Type":"text/csv"},body:text});const d=await res.json();if(!res.ok)setMessage(d.error);else if(commit){setMessage(`${d.count} artículos importados correctamente.`);setRows([]);setCsv("");}else{setRows(d.rows);setMessage(`${d.valid} filas válidas · ${d.invalid} con errores.`);}setPending(false);}
async function file(f:File){const text=await f.text();setCsv(text);await validate(text);}
return <div className="mx-auto max-w-5xl px-5 py-8 sm:px-8 lg:py-12"><Link href="/inventario" className="inline-flex items-center gap-2 text-xs font-semibold text-ink-soft"><ArrowLeft className="h-4 w-4"/>Volver</Link><h1 className="mt-5 font-display text-4xl font-semibold">Importar desde Excel</h1><p className="mt-2 text-sm text-ink-soft">Guarda la hoja como CSV UTF-8. Primero se valida; nada se escribe hasta que confirmes.</p><label className="mt-7 flex cursor-pointer flex-col items-center rounded-3xl border-2 border-dashed border-line bg-cream p-10 text-center"><FileSpreadsheet className="h-8 w-8 text-gold"/><span className="mt-3 font-semibold">Seleccionar CSV de Excel</span><input type="file" accept=".csv,text/csv" className="hidden" onChange={(e)=>e.target.files?.[0]&&void file(e.target.files[0])}/>{pending&&<Loader2 className="mt-3 h-5 w-5 animate-spin"/>}</label>{message&&<p className="mt-4 rounded-xl border border-line bg-cream p-3 text-sm">{message}</p>}{rows.length>0&&<><div className="mt-6 overflow-x-auto rounded-2xl border border-line bg-cream"><table className="w-full text-left text-xs"><thead><tr className="bg-paper"><th className="p-3">Fila</th><th>Nombre</th><th>Zona</th><th>Cantidad</th><th>Resultado</th></tr></thead><tbody>{rows.map(r=><tr key={r.row} className="border-t border-line-soft"><td className="p-3">{r.row}</td><td>{r.name}</td><td>{r.zone}</td><td>{r.quantity}</td><td className={r.errors.length?"text-red-700":"text-emerald-700"}>{r.errors.length?r.errors.join(", "):"Válida"}</td></tr>)}</tbody></table></div><Button variant="dark" className="mt-4" disabled={pending||invalid>0} onClick={()=>void validate(csv,true)}>{pending?<Loader2 className="h-4 w-4 animate-spin"/>:<Upload className="h-4 w-4"/>}Importar {rows.length} artículos ahora</Button>{invalid>0&&<p className="mt-2 text-xs text-red-700">Corrige las {invalid} filas marcadas y vuelve a seleccionar el archivo.</p>}</>}</div>}
