"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Check, Hammer, Handshake, Loader2 } from "lucide-react";
import type { Loan, MaintenanceRecord } from "@/db/schema";
import { Button, Field, inputCls } from "@/components/ui";
import { secureFetch } from "@/lib/secure-fetch";
import { formatDate } from "@/lib/utils";

export function ItemCarePanel({ itemId, itemType, quantity, loans, maintenance }: { itemId: number; itemType: string; quantity: number; loans: Loan[]; maintenance: MaintenanceRecord[] }) {
  const router = useRouter(); const [tab, setTab] = useState<"loan" | "maintenance">("loan"); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  async function post(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setPending(true); setError(null); const fd = new FormData(e.currentTarget); const endpoint = tab === "loan" ? "loans" : "maintenance"; const res = await secureFetch(`/api/items/${itemId}/${endpoint}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(fd)) }); const data = await res.json(); if (!res.ok) setError(data.error); else { e.currentTarget.reset(); router.refresh(); } setPending(false); }
  async function finish(endpoint: "loans" | "maintenance", id: number) { setPending(true); const res = await secureFetch(`/api/items/${itemId}/${endpoint}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(endpoint === "loans" ? { loanId: id } : { recordId: id }) }); if (!res.ok) setError((await res.json()).error); else router.refresh(); setPending(false); }
  const activeLoans = loans.filter((l) => !l.returnedAt); const activeMaintenance = maintenance.filter((m) => !m.completedAt);
  return <section className="rounded-3xl border border-line bg-cream p-5 shadow-card sm:p-6"><div className="flex gap-2"><button onClick={() => setTab("loan")} className={`cursor-pointer rounded-full px-4 py-2 text-xs font-bold ${tab === "loan" ? "bg-ink text-cream" : "bg-white text-ink-soft"}`}><Handshake className="mr-1 inline h-3.5 w-3.5" />Préstamos ({activeLoans.length})</button><button onClick={() => setTab("maintenance")} className={`cursor-pointer rounded-full px-4 py-2 text-xs font-bold ${tab === "maintenance" ? "bg-ink text-cream" : "bg-white text-ink-soft"}`}><Hammer className="mr-1 inline h-3.5 w-3.5" />Mantenimiento ({activeMaintenance.length})</button></div>
    {tab === "loan" ? <><ul className="mt-4 space-y-2">{activeLoans.map((l) => <li key={l.id} className="flex items-center gap-3 rounded-xl border border-sky-200 bg-sky-50 p-3 text-xs"><span className="flex-1"><strong>{l.borrower}</strong> · {l.quantity} ud. {l.dueAt && `· vence ${formatDate(l.dueAt)}`}</span><Button size="sm" variant="outline" onClick={() => void finish("loans", l.id)}><Check className="h-3 w-3" />Devuelto</Button></li>)}</ul><form onSubmit={post} className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Prestar a"><input name="borrower" required className={inputCls} /></Field><Field label="Responsable"><input name="responsible" className={inputCls} /></Field><Field label="Cantidad"><input name="quantity" type="number" min={1} max={itemType === "CONTABLE" ? quantity : 1} defaultValue={1} className={inputCls} /></Field><Field label="Devolución prevista"><input name="dueAt" type="date" className={inputCls} /></Field><div className="sm:col-span-2"><Button type="submit" disabled={pending}>{pending && <Loader2 className="h-4 w-4 animate-spin" />}Registrar préstamo</Button></div></form></> : <><ul className="mt-4 space-y-2">{activeMaintenance.map((m) => <li key={m.id} className="flex items-center gap-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs"><span className="flex-1"><strong>{m.description}</strong> {m.provider && `· ${m.provider}`} {m.nextReviewAt && `· próxima ${formatDate(m.nextReviewAt)}`}</span><Button size="sm" variant="outline" onClick={() => void finish("maintenance", m.id)}><Check className="h-3 w-3" />Finalizar</Button></li>)}</ul><form onSubmit={post} className="mt-4 grid gap-3 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Trabajo / incidencia"><input name="description" required className={inputCls} /></Field></div><Field label="Taller / restaurador"><input name="provider" className={inputCls} /></Field><Field label="Coste (€)"><input name="cost" type="number" min={0} step="0.01" className={inputCls} /></Field><Field label="Fecha inicio"><input name="startedAt" type="date" required defaultValue={new Date().toISOString().slice(0, 10)} className={inputCls} /></Field><Field label="Próxima revisión"><input name="nextReviewAt" type="date" className={inputCls} /></Field><div className="sm:col-span-2"><Button type="submit" disabled={pending}>{pending && <Loader2 className="h-4 w-4 animate-spin" />}Registrar mantenimiento</Button></div></form></>}
    {error && <p className="mt-3 text-sm text-red-700">{error}</p>}
  </section>;
}
