"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Loader2, Plus, Save, ToggleLeft, ToggleRight, Trash2 } from "lucide-react";
import type { AppSetting, Category, StorageLocation, Zone } from "@/db/schema";
import { Button, Field, inputCls } from "@/components/ui";
import { secureFetch } from "@/lib/secure-fetch";

export function SettingsManager({ settings, categories, zones, locations }: { settings: AppSetting; categories: Category[]; zones: Zone[]; locations: StorageLocation[] }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const [categoryName, setCategoryName] = useState(""); const [locationName, setLocationName] = useState(""); const [zoneId, setZoneId] = useState(zones[0]?.id ?? 0); const [parentId, setParentId] = useState(0);
  async function saveSettings(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setPending(true); const fd = new FormData(e.currentTarget); const res = await secureFetch("/api/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(fd)) }); const data = await res.json(); setMessage(res.ok ? "Ajustes guardados." : data.error); setPending(false); router.refresh(); }
  async function addCategory(e: FormEvent) { e.preventDefault(); if (!categoryName.trim()) return; setPending(true); const res = await secureFetch("/api/categories", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: categoryName }) }); const data = await res.json(); setMessage(res.ok ? "Categoría creada." : data.error); if (res.ok) setCategoryName(""); setPending(false); router.refresh(); }
  async function toggleCategory(c: Category) { await secureFetch("/api/categories", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: c.id, active: !c.active }) }); router.refresh(); }
  async function addLocation(e: FormEvent) { e.preventDefault(); if (!locationName.trim() || !zoneId) return; setPending(true); const res = await secureFetch("/api/locations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: locationName, zoneId, parentId: parentId || null, kind: parentId ? "ESTANTE" : "ARMARIO" }) }); const data = await res.json(); setMessage(res.ok ? "Ubicación creada." : data.error); if (res.ok) setLocationName(""); setPending(false); router.refresh(); }
  async function deleteLocation(id: number) { const res = await secureFetch(`/api/locations/${id}`, { method: "DELETE" }); const data = await res.json(); setMessage(res.ok ? "Ubicación eliminada." : data.error); router.refresh(); }
  return <div className="mx-auto max-w-4xl px-5 py-8 sm:px-8 lg:py-12">
    <header><p className="text-[0.65rem] font-semibold uppercase tracking-[0.28em] text-gold">Configuración</p><h1 className="mt-2 font-display text-4xl font-semibold text-ink">Ajustes</h1><p className="mt-2 text-sm text-ink-soft">Personaliza la parroquia y los catálogos sin modificar código.</p></header>
    {message && <p className="mt-5 rounded-xl border border-line bg-cream px-4 py-3 text-sm font-semibold text-ink">{message}</p>}
    <form onSubmit={saveSettings} className="mt-7 rounded-3xl border border-line bg-cream p-5 shadow-card sm:p-6"><h2 className="font-display text-xl font-semibold">Parroquia y códigos</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Nombre"><input name="parishName" defaultValue={settings.parishName} className={inputCls} /></Field><Field label="Prefijo de inventario"><input name="inventoryPrefix" defaultValue={settings.inventoryPrefix} maxLength={6} className={`${inputCls} font-mono uppercase`} /></Field><Field label="Dirección"><input name="address" defaultValue={settings.address ?? ""} className={inputCls} /></Field><Field label="Pie de etiqueta"><input name="labelFooter" defaultValue={settings.labelFooter ?? ""} className={inputCls} /></Field></div><Button type="submit" variant="dark" className="mt-4" disabled={pending}>{pending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Guardar</Button></form>
    <section className="mt-6 rounded-3xl border border-line bg-cream p-5 shadow-card sm:p-6"><h2 className="font-display text-xl font-semibold">Categorías</h2><form onSubmit={addCategory} className="mt-4 flex gap-2"><input value={categoryName} onChange={(e) => setCategoryName(e.target.value)} placeholder="Nueva categoría" className={inputCls} /><Button type="submit"><Plus className="h-4 w-4" />Añadir</Button></form><ul className="mt-4 divide-y divide-line-soft">{categories.map((c) => <li key={c.id} className="flex items-center gap-3 py-2.5"><span className={`flex-1 text-sm ${c.active ? "text-ink" : "line-through text-ink-faint"}`}>{c.name}</span><button onClick={() => void toggleCategory(c)} className="cursor-pointer text-ink-soft">{c.active ? <ToggleRight className="h-5 w-5 text-emerald-600" /> : <ToggleLeft className="h-5 w-5" />}</button></li>)}</ul></section>
    <section className="mt-6 rounded-3xl border border-line bg-cream p-5 shadow-card sm:p-6"><h2 className="font-display text-xl font-semibold">Armarios, estantes y cajas</h2><form onSubmit={addLocation} className="mt-4 grid gap-2 sm:grid-cols-4"><select value={zoneId} onChange={(e) => { setZoneId(Number(e.target.value)); setParentId(0); }} className={inputCls}>{zones.map((z) => <option key={z.id} value={z.id}>{z.name}</option>)}</select><select value={parentId} onChange={(e) => setParentId(Number(e.target.value))} className={inputCls}><option value={0}>Sin padre (armario)</option>{locations.filter((l) => l.zoneId === zoneId).map((l) => <option key={l.id} value={l.id}>{l.name}</option>)}</select><input value={locationName} onChange={(e) => setLocationName(e.target.value)} placeholder="Nombre" className={inputCls} /><Button type="submit"><Plus className="h-4 w-4" />Crear</Button></form><ul className="mt-4 divide-y divide-line-soft">{locations.map((l) => <li key={l.id} className="flex items-center gap-3 py-2.5 text-sm"><span className="flex-1">{zones.find((z) => z.id === l.zoneId)?.name} · {l.parentId ? "↳ " : ""}{l.name}</span><button onClick={() => void deleteLocation(l.id)} className="cursor-pointer text-ink-faint hover:text-red-600"><Trash2 className="h-4 w-4" /></button></li>)}</ul></section>
  </div>;
}
