import { NextRequest, NextResponse } from "next/server";
import { eq, sql } from "drizzle-orm";
import { db } from "@/db";
import { items, maintenanceRecords, movements } from "@/db/schema";
import { apiAuthGuard } from "@/lib/auth";
type Ctx = { params: Promise<{ id: string }> };
export async function POST(request: NextRequest, ctx: Ctx) {
  const denied = await apiAuthGuard(); if (denied) return denied; const { id: raw } = await ctx.params; const itemId = Number(raw); const b = await request.json().catch(() => null); const description = typeof b?.description === "string" ? b.description.trim() : "";
  if (!Number.isInteger(itemId) || !description || !/^\d{4}-\d{2}-\d{2}$/.test(String(b.startedAt ?? ""))) return NextResponse.json({ error: "Descripción y fecha de inicio son obligatorias." }, { status: 400 });
  const cost = b.cost === "" || b.cost == null ? null : Number(b.cost); if (cost !== null && (!Number.isFinite(cost) || cost < 0)) return NextResponse.json({ error: "Coste no válido." }, { status: 400 });
  const [record] = await db.transaction(async (tx) => { const [r] = await tx.insert(maintenanceRecords).values({ itemId, description: description.slice(0, 1000), provider: String(b.provider ?? "").trim().slice(0, 160) || null, cost: cost !== null ? cost.toFixed(2) : null, startedAt: b.startedAt, nextReviewAt: b.nextReviewAt || null, notes: String(b.notes ?? "").trim().slice(0, 500) || null }).returning(); await tx.update(items).set({ status: "MANTENIMIENTO", version: sql`${items.version} + 1`, updatedAt: new Date() }).where(eq(items.id, itemId)); await tx.insert(movements).values({ itemId, type: "MANTENIMIENTO", note: `${description}${r.provider ? ` · ${r.provider}` : ""}` }); return [r]; }); return NextResponse.json(record, { status: 201 });
}
export async function PATCH(request: NextRequest, ctx: Ctx) { const denied = await apiAuthGuard(); if (denied) return denied; const { id: raw } = await ctx.params; const itemId = Number(raw); const b = await request.json().catch(() => null); const recordId = Number(b?.recordId); if (!Number.isInteger(recordId)) return NextResponse.json({ error: "Registro no válido." }, { status: 400 }); const [record] = await db.transaction(async (tx) => { const [r] = await tx.update(maintenanceRecords).set({ completedAt: new Date().toISOString().slice(0, 10) }).where(eq(maintenanceRecords.id, recordId)).returning(); if (!r || r.itemId !== itemId) throw new Error(); await tx.update(items).set({ status: "DISPONIBLE", version: sql`${items.version} + 1`, updatedAt: new Date() }).where(eq(items.id, itemId)); await tx.insert(movements).values({ itemId, type: "MANTENIMIENTO_FIN", note: "Mantenimiento finalizado" }); return [r]; }).catch(() => []); return record ? NextResponse.json(record) : NextResponse.json({ error: "Registro no encontrado." }, { status: 404 }); }
